INSERT INTO `vehicle` (`id_vehicle`, `anio_fabricacion`, `cantidad_ruedas`, `marca`, `modelo`, `patente`) VALUES
                                                                                                              (1, 2023, 2, 'Yamaha', 'MT-07', 'RSD12S'),
                                                                                                              (2, 2005, 4, 'Toyota', 'Camry', 'TYS56R'),
                                                                                                              (3, 2024, 2, 'Harley-Davidson', 'Sportster', 'HND89T'),
                                                                                                              (4, 2008, 4, 'Chevrolet', 'Silverado', 'CVT21U'),
                                                                                                              (5, 2015, 2, 'Honda', 'CBR600RR', 'VWP45W'),
                                                                                                              (6, 2022, 4, 'BMW', 'X5', 'BMW76J'),
                                                                                                              (7, 2003, 4, 'Audi', 'A4', 'ADI23Y'),
                                                                                                              (8, 2020, 2, 'Kawasaki', 'Ninja 650', 'MBZ12Q'),
                                                                                                              (9, 2019, 4, 'Hyundai', 'Tucson', 'HYD67A'),
                                                                                                              (10, 2021, 2, 'Suzuki', 'GSX-R750', 'KIA90L'),
                                                                                                              (11, 2001, 4, 'Subaru', 'Impreza', 'SBR34R'),
                                                                                                              (12, 2024, 2, 'Ducati', 'Panigale V2', 'TSL09M'),
                                                                                                              (13, 2007, 4, 'Nissan', 'Altima', 'NSN78S'),
                                                                                                              (14, 2016, 2, 'Triumph', 'Street Triple', 'MZD55K'),
                                                                                                              (15, 2010, 4, 'Ford', 'Mustang', 'FGT34P'),
                                                                                                              (16, 2018, 4, 'Jeep', 'Wrangler', 'JEP18R'),
                                                                                                              (17, 2024, 2, 'BMW', 'M4', 'BMW24M'),
                                                                                                              (18, 2019, 2, 'Mazda', 'MX-5', 'MZD19X'),
                                                                                                              (19, 2023, 4, 'Ford', 'Explorer', 'FGT23P'),
                                                                                                              (20, 2020, 2, 'Tesla', 'Model S', 'TSL20S'),
                                                                                                              (21, 2024, 3, 'Volkswagen', 'Transporter', 'VW24T'),
                                                                                                              (22, 2024, 6, 'MAN', 'TGS', 'MAN24G'),
                                                                                                              (23, 2024, 8, 'Volvo', 'FH16', 'VOL24H'),
                                                                                                              (24, 2024, 10, 'Scania', 'R730', 'SCA24R'),
                                                                                                              (25, 2024, 12, 'Mercedes-Benz', 'Actros', 'MBZ24A'),
                                                                                                              (26, 2024, 16, 'DAF', 'XF', 'DAF24X'),
                                                                                                              (27, 2024, 18, 'Iveco', 'Stralis', 'IVE24S');
INSERT INTO `siniestro` (`id_siniestro`, `fecha_siniestro`, `precio_siniestro`, `vehiculo_id`) VALUES
                                                                                                   (1, '2024-06-10', 15000.0, 3),
                                                                                                   (2, '2024-06-12', 9000.0, 5),
                                                                                                   (3, '2024-06-15', 18000.0, 6),
                                                                                                   (4, '2024-06-18', 11000.0, 12),
                                                                                                   (5, '2024-06-20', 8000.0, 17),
                                                                                                   (6, '2024-06-22', 25000.0, 22),
                                                                                                   (7, '2024-06-25', 7500.0, 23),
                                                                                                   (8, '2024-06-28', 17000.0, 24),
                                                                                                   (9, '2024-06-30', 20000.0, 25),
                                                                                                   (10, '2024-07-02', 16000.0, 26);