SELECT * FROM movies;
SELECT first_name, last_name, rating  FROM actors;
SELECT title AS "Titulo de la serie" FROM series;
SELECT first_name, last_name FROM actors WHERE rating > 7.5;
SELECT title, rating, awards FROM movies WHERE (rating > 7.5 AND awards > 2);
SELECT title, rating FROM movies ORDER BY rating ASC;
SELECT title FROM movies LIMIT 3;
SELECT title FROM movies ORDER BY rating DESC limit 5;
SELECT first_name , last_name  FROM actors limit 10;
SELECT title, rating from movies WHERE title = 'Toy Story';
SELECT first_name, last_name from actors WHERE first_name = 'Sam';
SELECT title from movies WHERE release_date > '2004-01-01' AND release_date < '2008-01-01';
SELECT title, rating , awards  from movies WHERE rating > 3 and awards > 1 AND release_date > '1988-01-01' AND release_date < '2009-01-01' ORDER BY rating DESC;
