# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 500000
    keepalive: 200000
    db: FRESHMARKE
    host: DB_MYSQL_DESAENV09_FRESHMARKE_FRESHMARKE_ENDPOINT
    user: FRESHMARKE_WPROD
    password: DB_MYSQL_DESAENV09_FRESHMARKE_FRESHMARKE_WPROD
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update