# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: h2
db:
  host: localhost:8080
  username: admin
  password: admin
  name: bdtest
  url: jdbc:h2:mem:navin
  driver:
    name: org.h2.Driver

meli:
  base:
    url: https://api.mercadolibre.com
