# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: DB_MYSQL_DESAENV09_FRESHPRODS_FRESHPRODS_ENDPOINT
    db: freshprods
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: freshprods_WPROD
    password: DB_MYSQL_DESAENV09_FRESHPRODS_FRESHPRODS_WPROD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update