repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1  # Puedes verificar la última versión en el repositorio oficial
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
