
## Properties file for local/dev environment
## You need to configure the environment variable in your IDE, more info in README.md
## Overrides application.yml default properties


spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:frescosmel
    username: admin
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
