# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: DB_MYSQL_DESAENV09_PAGUZMANDB_PAGUZMANDB_ENDPOINT
    db: PAguzmanDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    username: PAguzmanDB_WPROD
    password: DB_MYSQL_DESAENV09_PAGUZMANDB_PAGUZMANDB_WPROD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: none