# Properties file for integration tests
# Overrides application.yml default properties

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081
  servlet:
    context-path: /api/v1
