
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db: DbTeam1
    username: DbTeam1_WPROD
    password: DB_MYSQL_DESAENV09_DBTEAM1_DBTEAM1_WPROD
    host: DB_MYSQL_DESAENV09_DBTEAM1_DBTEAM1_ENDPOINT
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none



#server:
   # servlet:
    #  context-path: /api/v1


