# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    host: DB_MYSQL_DESAENV09_FPRODS_FPRODS_ENDPOINT
    db: fprods
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fprods_WPROD
    password: DB_MYSQL_DESAENV09_FPRODS_FPRODS_WPROD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update