# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: DB_MYSQL_DESAENV09_PRODUCTDB7_PRODUCTDB7_ENDPOINT
    db: productdb7
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    username: productdb7_WPROD
    password: DB_MYSQL_DESAENV09_PRODUCTDB7_PRODUCTDB7_WPROD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
