# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: DB_MYSQL_DESAENV09_TEAM6DB_TEAM6DB_ENDPOINT
    db: team6db
    username: team6db_WPROD
    password: DB_MYSQL_DESAENV09_TEAM6DB_TEAM6DB_WPROD
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update