# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST_URI}/${DB_SCHEMA}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
  sql:
    init:
      mode: always

secrets:
  JWT_SECRET: UHJ1ZWJhczEyMzQ1Njc4OV9NZWxUZXN0OTg3NjU0MzIxMEZ1cnkgVGVzdCAxMjM0MzI1NjU3ODM1NDg5NzlBLVotMC0x

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: never
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USER}
#    password: ${DB_PASS}
#    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/productdb7?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
