# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: DB_MYSQL_DESAENV09_BATFINBOOT_BATFINBOOT_ENDPOINT
    db: batfinboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    username: batfinboot_WPROD
    password: DB_MYSQL_DESAENV09_BATFINBOOT_BATFINBOOT_WPROD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
