{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "pf-be-hisp-w26-t10-meza",
    "description" : "pf-be-hisp-w26-t10-meza",
    "contact" : {
      "name" : "jgarciavarga",
      "email" : "johnstiven.garciavargas@mercadolibre.com.co"
    },
    "version" : "last"
  },
  "servers" : [ {
    "url" : "https://test_pf-be-hisp-w26-t10-meza.furyapps.io",
    "description" : "Scope test"
  } ],
  "paths" : {
    "/api/v1/fresh-products/{idSeller}/{idProduct}" : {
      "put" : {
        "tags" : [ "product-controller" ],
        "operationId" : "updateProducts",
        "parameters" : [ {
          "name" : "idSeller",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/ProductInfoDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ProductLoadResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/orders/{idOrder}" : {
      "get" : {
        "tags" : [ "fresh-products-controller" ],
        "operationId" : "getProductsFromCart",
        "parameters" : [ {
          "name" : "idOrder",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "fresh-products-controller" ],
        "operationId" : "modifyOrder",
        "parameters" : [ {
          "name" : "idOrder",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PurchaseOrderRequestBodyDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/inboundorder" : {
      "put" : {
        "tags" : [ "fresh-products-controller" ],
        "operationId" : "updateBatchStock",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UploadBatchRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseDto"
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "fresh-products-controller" ],
        "operationId" : "addBatchIntoStock",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UploadBatchRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/warehouse/register" : {
      "post" : {
        "tags" : [ "warehouse-controller" ],
        "operationId" : "registerWarehouse",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/WarehouseInfoDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/WarehouseResponseRegisterDto"
                }
              }
            }
          }
        }
      }
    },
    "/auth/login" : {
      "post" : {
        "tags" : [ "auth-controller" ],
        "operationId" : "login",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/LoginRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idSeller}" : {
      "post" : {
        "tags" : [ "product-controller" ],
        "operationId" : "loadProduct",
        "parameters" : [ {
          "name" : "idSeller",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/ProductLoadRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ProductLoadResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/orders" : {
      "post" : {
        "tags" : [ "fresh-products-controller" ],
        "operationId" : "saveOrder",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PurchaseOrderDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/warehouse/{idWarehouse}" : {
      "get" : {
        "tags" : [ "warehouse-controller" ],
        "operationId" : "getOneWarehouse",
        "parameters" : [ {
          "name" : "idWarehouse",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/ping" : {
      "get" : {
        "tags" : [ "ping-controller" ],
        "operationId" : "ping",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idProduct}/warehouse/list" : {
      "get" : {
        "tags" : [ "product-controller" ],
        "operationId" : "getItemQtyByWh",
        "parameters" : [ {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idProduct}/batch/list" : {
      "get" : {
        "tags" : [ "frescos-controller" ],
        "operationId" : "getFescos",
        "parameters" : [ {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "order",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/list" : {
      "get" : {
        "tags" : [ "product-controller" ],
        "operationId" : "getAllProducts",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/ProductsGeneralDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/batch/list/due-date/{cantDays}" : {
      "get" : {
        "tags" : [ "fresh-products-controller" ],
        "operationId" : "getBatchExpiringInDaysOrdered",
        "parameters" : [ {
          "name" : "cantDays",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "category",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "order",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ProductInfoDto" : {
        "required" : [ "price", "product_category", "product_desc" ],
        "type" : "object",
        "properties" : {
          "price" : {
            "type" : "number",
            "format" : "double"
          },
          "product_category" : {
            "type" : "integer",
            "format" : "int32"
          },
          "product_desc" : {
            "type" : "string"
          }
        }
      },
      "ProductLoadResponseDto" : {
        "type" : "object",
        "properties" : {
          "operation" : {
            "type" : "integer",
            "format" : "int32"
          },
          "message" : {
            "type" : "string"
          },
          "code" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "PurchaseOrderProduct" : {
        "type" : "object",
        "properties" : {
          "product_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "quantity" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "PurchaseOrderRequestBodyDto" : {
        "type" : "object",
        "properties" : {
          "purchase_order" : {
            "$ref" : "#/components/schemas/PurchaseOrderRequestDto"
          }
        }
      },
      "PurchaseOrderRequestDto" : {
        "type" : "object",
        "properties" : {
          "date" : {
            "type" : "string"
          },
          "buyer_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_status" : {
            "$ref" : "#/components/schemas/PurchaseOrderStatusDto"
          },
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PurchaseOrderProduct"
            }
          }
        }
      },
      "PurchaseOrderStatusDto" : {
        "type" : "object",
        "properties" : {
          "status_code" : {
            "type" : "string"
          }
        }
      },
      "BatchDto" : {
        "required" : [ "batch_number", "current_quantity", "current_temperature", "due_date", "initial_quantity", "manufacturing_date", "manufacturing_time", "minimum_temperature", "product_id" ],
        "type" : "object",
        "properties" : {
          "product_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "batch_number" : {
            "type" : "integer",
            "format" : "int32"
          },
          "current_temperature" : {
            "type" : "number",
            "format" : "double"
          },
          "minimum_temperature" : {
            "type" : "number",
            "format" : "double"
          },
          "initial_quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "current_quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "manufacturing_date" : {
            "type" : "string",
            "format" : "date"
          },
          "manufacturing_time" : {
            "$ref" : "#/components/schemas/LocalTime"
          },
          "due_date" : {
            "type" : "string",
            "format" : "date"
          }
        }
      },
      "InboundOrderDto" : {
        "required" : [ "batch_stock", "order_date", "order_number", "section" ],
        "type" : "object",
        "properties" : {
          "order_number" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_date" : {
            "type" : "string",
            "format" : "date"
          },
          "section" : {
            "$ref" : "#/components/schemas/SectionDto"
          },
          "batch_stock" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BatchDto"
            }
          }
        }
      },
      "LocalTime" : {
        "type" : "object",
        "properties" : {
          "hour" : {
            "type" : "integer",
            "format" : "int32"
          },
          "minute" : {
            "type" : "integer",
            "format" : "int32"
          },
          "second" : {
            "type" : "integer",
            "format" : "int32"
          },
          "nano" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "SectionDto" : {
        "required" : [ "section_code", "warehouse_code" ],
        "type" : "object",
        "properties" : {
          "section_code" : {
            "type" : "integer",
            "format" : "int32"
          },
          "warehouse_code" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "UploadBatchRequestDto" : {
        "required" : [ "inbound_order" ],
        "type" : "object",
        "properties" : {
          "inbound_order" : {
            "$ref" : "#/components/schemas/InboundOrderDto"
          }
        }
      },
      "BatchResponseDto" : {
        "type" : "object",
        "properties" : {
          "batch_stock" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BatchDto"
            }
          }
        }
      },
      "WarehouseInfoDto" : {
        "required" : [ "supervisor_id", "warehouse_name" ],
        "type" : "object",
        "properties" : {
          "warehouse_name" : {
            "type" : "string"
          },
          "supervisor_id" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      },
      "WarehouseResponseRegisterDto" : {
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string"
          }
        }
      },
      "LoginRequestDto" : {
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      },
      "ProductLoadRequestDto" : {
        "required" : [ "products" ],
        "type" : "object",
        "properties" : {
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ProductInfoDto"
            }
          }
        }
      },
      "OrderStatusDto" : {
        "type" : "object",
        "properties" : {
          "status_code" : {
            "type" : "string"
          }
        }
      },
      "ProductRequestDto" : {
        "type" : "object",
        "properties" : {
          "quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "product_id" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "PurchaseOrderDetailsDto" : {
        "type" : "object",
        "properties" : {
          "date" : {
            "type" : "string",
            "format" : "date"
          },
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ProductRequestDto"
            }
          },
          "buyer_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_status" : {
            "$ref" : "#/components/schemas/OrderStatusDto"
          }
        }
      },
      "PurchaseOrderDto" : {
        "type" : "object",
        "properties" : {
          "purchase_order" : {
            "$ref" : "#/components/schemas/PurchaseOrderDetailsDto"
          }
        }
      },
      "ProductsGeneralDto" : {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "price" : {
            "type" : "number",
            "format" : "double"
          }
        }
      }
    }
  }
}
