{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "sprint-3-team-12",
    "description" : "sprint-3-team-12",
    "contact" : {
      "name" : "yvalderrama",
      "email" : "yair.valderrama@mercadolibre.com.mx"
    },
    "version" : "last"
  },
  "servers" : [ {
    "url" : "http://localhost:8080",
    "description" : "Scope local"
  } ],
  "paths" : {
    "/api/v1/fresh-products/updateproduct" : {
      "put" : {
        "tags" : [ "product-controller" ],
        "operationId" : "updateProduct",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/ProductAddDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/orders/{idOrder}" : {
      "get" : {
        "tags" : [ "cart-controller" ],
        "operationId" : "getCart",
        "parameters" : [ {
          "name" : "idOrder",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CartDTO"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "in-bound-order-controller" ],
        "operationId" : "createInboundOrder",
        "parameters" : [ {
          "name" : "idOrder",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CartDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/inboundorder" : {
      "put" : {
        "tags" : [ "in-bound-order-controller" ],
        "operationId" : "updateInboundOrder",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/InboundDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "in-bound-order-controller" ],
        "operationId" : "newInboundOrder",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/InboundDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/auth/register" : {
      "post" : {
        "tags" : [ "auth-controller" ],
        "operationId" : "register",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/RegisterRequestDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/auth/registerAdmin" : {
      "post" : {
        "tags" : [ "auth-controller" ],
        "operationId" : "registerAdmin",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/RegisterRequestDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/auth/login" : {
      "post" : {
        "tags" : [ "auth-controller" ],
        "operationId" : "login",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/LoginRequestDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/orders" : {
      "post" : {
        "tags" : [ "in-bound-order-controller" ],
        "operationId" : "createInboundOrder_1",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CartDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/createproduct" : {
      "post" : {
        "tags" : [ "product-controller" ],
        "operationId" : "postProducts",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/ProductInjectionDTO"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/ping" : {
      "get" : {
        "tags" : [ "ping-controller" ],
        "operationId" : "ping",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/index2" : {
      "get" : {
        "tags" : [ "demo-controller" ],
        "operationId" : "index2",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idProduct}/warehouse/list" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getAllWarehouseStock",
        "parameters" : [ {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idProduct}/batch/list" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getWareHouse",
        "parameters" : [ {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "order",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/list" : {
      "get" : {
        "tags" : [ "product-controller" ],
        "operationId" : "getProducts",
        "parameters" : [ {
          "name" : "category",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ResponseProductDTO"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/batch/list/due-date/{cantDays}" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getDueBatchesByDays",
        "parameters" : [ {
          "name" : "cantDays",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/batch/list/due-date/f/{cantDays}" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getDueBatchesByDaysAndCategory",
        "parameters" : [ {
          "name" : "cantDays",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "category",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "FS", "RF", "FF" ]
          }
        }, {
          "name" : "order",
          "in" : "query",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/demo" : {
      "get" : {
        "tags" : [ "demo-controller" ],
        "operationId" : "index",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/demoAdmin" : {
      "get" : {
        "tags" : [ "demo-controller" ],
        "operationId" : "indexAdmin",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ProductAddDTO" : {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "product_desc" : {
            "type" : "string"
          },
          "price" : {
            "type" : "number",
            "format" : "double"
          },
          "type" : {
            "type" : "string",
            "enum" : [ "FS", "RF", "FF" ]
          }
        }
      },
      "CartDTO" : {
        "required" : [ "purchase_order" ],
        "type" : "object",
        "properties" : {
          "purchase_order" : {
            "$ref" : "#/components/schemas/PurchaseOrderDTO"
          }
        }
      },
      "OrderStatusDTO" : {
        "required" : [ "status_code" ],
        "type" : "object",
        "properties" : {
          "status_code" : {
            "type" : "string"
          }
        }
      },
      "ProductDTO" : {
        "required" : [ "product_id", "quantity" ],
        "type" : "object",
        "properties" : {
          "product_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "quantity" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "PurchaseOrderDTO" : {
        "required" : [ "buyer_id", "order_status", "products" ],
        "type" : "object",
        "properties" : {
          "date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "buyer_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_status" : {
            "$ref" : "#/components/schemas/OrderStatusDTO"
          },
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ProductDTO"
            }
          }
        }
      },
      "BatchDTO" : {
        "required" : [ "batch_number", "current_quantity", "current_temperature", "due_date", "initial_quantity", "manufacturing_date", "manufacturing_time", "minimum_temperature", "product_id" ],
        "type" : "object",
        "properties" : {
          "batch_number" : {
            "type" : "integer",
            "format" : "int32"
          },
          "product_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "current_temperature" : {
            "type" : "number",
            "format" : "double"
          },
          "minimum_temperature" : {
            "type" : "number",
            "format" : "double"
          },
          "initial_quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "current_quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "manufacturing_date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "manufacturing_time" : {
            "type" : "string",
            "format" : "date-time"
          },
          "due_date" : {
            "type" : "string",
            "format" : "date-time"
          }
        }
      },
      "InboundDTO" : {
        "type" : "object",
        "properties" : {
          "inbound_order" : {
            "$ref" : "#/components/schemas/InboundOrderDTO"
          }
        }
      },
      "InboundOrderDTO" : {
        "required" : [ "batch_stock", "order_date", "order_number", "section" ],
        "type" : "object",
        "properties" : {
          "order_number" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "section" : {
            "$ref" : "#/components/schemas/SectionDTO"
          },
          "batch_stock" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BatchDTO"
            }
          }
        }
      },
      "SectionDTO" : {
        "required" : [ "section_code", "warehouse_code" ],
        "type" : "object",
        "properties" : {
          "section_code" : {
            "type" : "integer",
            "format" : "int32"
          },
          "warehouse_code" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "RegisterRequestDTO" : {
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "first_name" : {
            "type" : "string"
          },
          "last_name" : {
            "type" : "string"
          }
        }
      },
      "LoginRequestDTO" : {
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      },
      "ProductInjectionDTO" : {
        "type" : "object",
        "properties" : {
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ProductAddDTO"
            }
          }
        }
      },
      "ResponseProductDTO" : {
        "type" : "object",
        "properties" : {
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ProductDTO"
            }
          }
        }
      }
    }
  }
}