# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:melifreskos
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true