# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      max-lifetime: 500000
      keepalive-time: 200000
  jpa:
    hibernate:
      ddl-auto: create-drop