INSERT INTO roles VALUES(1,'Seller','Seller');
INSERT INTO categories VALUES(1,'fresco','fresco');

-- EL INSERT DE USUARIOS SE HACE DESDE ACA PARA PODER LOGUEARSE Y TIRAR PETICIONES.
-- PARA LOGUEAR, SE DEBE UTILIZAR EMAIL Y PASSWORD = 'chona'.
-- EN LA BASE LA PASSWORD SE GUARDA DISTINTO, YA QUE DESDE LA APP SE ENCRIPTA
INSERT INTO users(email,password,username,id_role) VALUES ('chonagmail.com','$2a$10$T6RLGvpvuOuGXrtfeWEJgeynyq.ogLd9AZRqeVxDpH5FLLuPxWIdi','chona',1);
