{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "project-java-w26-team13",
    "description" : "project-java-w26-team13",
    "contact" : {
      "name" : "gpalomo",
      "email" : "gonzalo.palomo@mercadolibre.com"
    },
    "version" : "last"
  },
  "servers" : [ {
    "url" : "http://localhost:8080",
    "description" : "Scope local"
  } ],
  "paths" : {
    "/api/v1/fresh-products/orders/{idOrder}" : {
      "get" : {
        "tags" : [ "cart-controller" ],
        "operationId" : "getCart",
        "parameters" : [ {
          "name" : "idOrder",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CartRequestDto"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "cart-controller" ],
        "operationId" : "updateOrder",
        "parameters" : [ {
          "name" : "idOrder",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CartRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CartResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/inboundorder" : {
      "put" : {
        "tags" : [ "order-controller" ],
        "operationId" : "updateInboundOrder",
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/OrderRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "order-controller" ],
        "operationId" : "registerBatch",
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/OrderRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/auth/register" : {
      "post" : {
        "tags" : [ "auth-controller" ],
        "operationId" : "register",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/RegisterRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/auth/login" : {
      "post" : {
        "tags" : [ "auth-controller" ],
        "operationId" : "login",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/LoginRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/orders" : {
      "post" : {
        "tags" : [ "cart-controller" ],
        "operationId" : "createCart",
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CartRequestDto"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CartResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/ping" : {
      "get" : {
        "tags" : [ "ping-controller" ],
        "operationId" : "ping",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idProduct}/warehouse/list" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getProductStockByWarehouse",
        "parameters" : [ {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/{idProduct}/batch/list" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getBatchesByProduct",
        "parameters" : [ {
          "name" : "idProduct",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "order",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/list" : {
      "get" : {
        "tags" : [ "product-controller" ],
        "operationId" : "getList",
        "parameters" : [ {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "category",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/fresh-products/batch/list/due-date/{cantDays}" : {
      "get" : {
        "tags" : [ "batch-controller" ],
        "operationId" : "getBatchesDueDate",
        "parameters" : [ {
          "name" : "cantDays",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "Authorization",
          "in" : "header",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "category",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "order",
          "in" : "query",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "CartProductDto" : {
        "type" : "object",
        "properties" : {
          "quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "product_id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "cart_detail_id" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      },
      "CartRequestDto" : {
        "type" : "object",
        "properties" : {
          "purchase_order" : {
            "$ref" : "#/components/schemas/PurchaseOrderDto"
          }
        }
      },
      "OrderStatusDto" : {
        "type" : "object",
        "properties" : {
          "status_code" : {
            "type" : "string"
          }
        }
      },
      "PurchaseOrderDto" : {
        "required" : [ "buyer_id", "date", "order_status", "products" ],
        "type" : "object",
        "properties" : {
          "products" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/CartProductDto"
            }
          },
          "date" : {
            "type" : "string"
          },
          "buyer_id" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_status" : {
            "$ref" : "#/components/schemas/OrderStatusDto"
          }
        }
      },
      "CartResponseDto" : {
        "type" : "object",
        "properties" : {
          "total_price" : {
            "type" : "number",
            "format" : "double"
          },
          "products_without_stock" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      },
      "BatchStockDto" : {
        "type" : "object",
        "properties" : {
          "batch_number" : {
            "type" : "string"
          },
          "product_id" : {
            "type" : "integer",
            "format" : "int64"
          },
          "current_temperature" : {
            "type" : "number",
            "format" : "double"
          },
          "minimum_temperature" : {
            "type" : "number",
            "format" : "double"
          },
          "initial_quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "current_quantity" : {
            "type" : "integer",
            "format" : "int32"
          },
          "manufacturing_date" : {
            "type" : "string",
            "format" : "date"
          },
          "manufacturing_time" : {
            "$ref" : "#/components/schemas/LocalTime"
          },
          "due_date" : {
            "type" : "string",
            "format" : "date"
          }
        }
      },
      "LocalTime" : {
        "type" : "object",
        "properties" : {
          "hour" : {
            "type" : "integer",
            "format" : "int32"
          },
          "minute" : {
            "type" : "integer",
            "format" : "int32"
          },
          "second" : {
            "type" : "integer",
            "format" : "int32"
          },
          "nano" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "OrderRequestDto" : {
        "type" : "object",
        "properties" : {
          "section" : {
            "$ref" : "#/components/schemas/SectionDto"
          },
          "order_number" : {
            "type" : "integer",
            "format" : "int32"
          },
          "order_date" : {
            "type" : "string",
            "format" : "date"
          },
          "batch_stock" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BatchStockDto"
            }
          }
        }
      },
      "SectionDto" : {
        "type" : "object",
        "properties" : {
          "section_code" : {
            "type" : "integer",
            "format" : "int64"
          },
          "warehouse_code" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      },
      "RegisterRequestDto" : {
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      },
      "LoginRequestDto" : {
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
