{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "sprint-3-team-12",
    "description" : "sprint3-individual-perez",
    "contact" : {
      "name" : "yvalderrama",
      "email" : "yair.valderrama@mercadolibre.com.mx"
    },
    "version" : "last"
  },
  "servers" : [ {
    "url" : "http://localhost:8080",
    "description" : "Scope local"
  } ],
  "paths" : { },
  "components" : { }
}