# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db: pfarguello
    username: pfarguello_WPROD
    password: DB_MYSQL_DESAENV09_PFARGUELLO_PFARGUELLO_WPROD
    host: DB_MYSQL_DESAENV09_PFARGUELLO_PFARGUELLO_ENDPOINT
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none



server:
  servlet:
    context-path: /api/v1
