### Insert Data 
POST http://localhost:9200/obras/_doc
Content-Type: application/json

{
  "nombre": "Algebra de Baldor",
  "autor": "Baldor",
  "cantidadPaginas": 2000,
  "editorial": "Editorial Salamanca",
  "anioPrimerPublicacion": 2005
}


### GET ALL 
GET http://localhost:9200/obras/_search

### 1. Obras por autor 
GET http://localhost:8080/obras?autor=Gabriel García Márquez

### 2. Obras palabras clave 
GET http://localhost:8080/obras/nombre?nombre=Bald

### 3. Top 5 con mayor cantidad de paginas
GET http://localhost:8080/obras/paginas

### 4. Retornar las obras que fueron publicadas antes de un anio 
GET http://localhost:8080/obras/years?year=2010

### 5. Retornar las obras de una editorial }
GET http://localhost:8080/obras/editorial?editorial=Sudamericana
